IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#DVA",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleFriendshipActive","GLOBAL",1)
Global("L#XzeleFriendshipTalk","GLOBAL",4)
RealGlobalTimerExpired("L#XzeleFriendTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleFriendshipTalk","GLOBAL",5)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#DVA",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleFriendshipActive","GLOBAL",1)
Global("L#XzeleFriendshipTalk","GLOBAL",7)
RealGlobalTimerExpired("L#XzeleFriendTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleFriendshipTalk","GLOBAL",8)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#DVA",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleFriendshipActive","GLOBAL",1)
Global("L#XzeleFriendshipTalk","GLOBAL",10)
RealGlobalTimerExpired("L#XzeleFriendTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleFriendshipTalk","GLOBAL",11)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleRomanceActive","GLOBAL",1)
Global("L#XzeleRomanceTalk","GLOBAL",7)
RealGlobalTimerExpired("L#XzeleRomanceTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleRomanceTalk","GLOBAL",8)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleRomanceActive","GLOBAL",1)
Global("L#XzeleRomanceTalk","GLOBAL",13)
RealGlobalTimerExpired("L#XzeleRomanceTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleRomanceTalk","GLOBAL",14)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleRomanceActive","GLOBAL",1)
Global("L#XzeleRomanceTalk","GLOBAL",22)
RealGlobalTimerExpired("L#XzeleRomanceTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleRomanceTalk","GLOBAL",23)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleRomanceActive","GLOBAL",1)
Global("L#XzeleRomanceTalk","GLOBAL",25)
RealGlobalTimerExpired("L#XzeleRomanceTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleRomanceTalk","GLOBAL",26)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!AreaType(DUNGEON)
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleRomanceActive","GLOBAL",1)
Global("L#XzeleRomanceTalk","GLOBAL",28)
RealGlobalTimerExpired("L#XzeleRomanceTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleRomanceTalk","GLOBAL",29)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
OR(3)
 AreaCheck("AR1512")
 AreaCheck("AR1513")
 AreaCheck("AR1514")
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleRomanceActive","GLOBAL",2)
Global("L#XzeleRomanceAsyTalk","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L#XzeleRomanceAsyTalk","GLOBAL",1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
OR(4)
 AreaCheck("AR2100")
 AreaCheck("AR2101")
 AreaCheck("AR2102")
 AreaCheck("AR2401")
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("L#XzeleRomanceActive","GLOBAL",2)
Global("L#XzeleRomanceUDTalk","GLOBAL",1)
RealGlobalTimerExpired("L#XzeleRomanceUDTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L#XzeleRomanceUDTalk","GLOBAL",2)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
RealGlobalTimerExpired("L#XZEComingOutMaleTime","GLOBAL")
Global("L#XZEComingOutMaleActive","GLOBAL",1)
Global("L#XZEComingOutMaleTalk","GLOBAL",7)
THEN
RESPONSE #100
SetGlobal("L#XZEComingOutMaleTalk","GLOBAL",8)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
!StateCheck("L#XZE",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
RealGlobalTimerExpired("L#XZEComingOutFemaleTime","GLOBAL")
Global("L#XZEComingOutFemaleActive","GLOBAL",1)
Global("L#XZEComingOutFemaleTalk","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("L#XZEComingOutFemaleTalk","GLOBAL",5)
END